#!/usr/bin/env bash
# Auto-generated by env-generator (uv backend) — DO NOT HAND-EDIT.
# Re-run via `/nautilus:env-generator` to regenerate.
# Project: genesis-world    Python: 3.10
set -euo pipefail

cd "$(dirname "$0")/.."   # cd to repo root

# --- Step 1: prerequisites ---
command -v uv >/dev/null 2>&1 || { echo "[setup_uv] uv not found — install via 'curl -fsSL https://astral.sh/uv/install.sh | sh'" >&2; exit 1; }

# --- Step 2: create venv (idempotent) ---
if [ ! -d .venv ]; then
  uv venv --python 3.10 .venv
else
  echo "[setup_uv] .venv already exists; reusing"
fi

# Activate venv for the rest of this script.
# shellcheck disable=SC1091
source .venv/bin/activate

# --- Step 3: install steps (translated from nautilus/install_plan.json) ---
# (system apt) NOT executed — uv backend cannot sudo. Run manually if imports fail:
#     sudo apt install -y libegl1 libosmesa6 libgl1 libglib2.0-0
uv sync --no-install-project --active
uv pip install torch --index-url https://download.pytorch.org/whl/cu126
uv pip install -e '.[dev]' --no-build-isolation

# --- Step 4: nautilus extras (logging + experiment tracking + RL deps) ---
# These are NOT in the upstream install plan — they're injected by env-generator
# so downstream subagents (benchmark-generator, rl-integration-generator) work
# out-of-the-box without extra build steps. Idempotent: uv pip install skips
# already-installed packages.

# DataLogger backends used by rl-integration-generator (TensorBoard + W&B).
uv pip install wandb tensorboardX
# Video writer used by benchmark-generator render_random.py (and rl render.py).
uv pip install 'imageio[ffmpeg]'
# Plotting used by rl train.py end-of-training learning-curve dump.
uv pip install matplotlib
# Hydra / OmegaConf used by all rl-integration-generator scripts (train/eval/render).
uv pip install hydra-core omegaconf
# Stable-Baselines3 (extra) for the rl-integration-generator stable_baseline3 path.
uv pip install 'stable_baselines3[extra]'

echo "[setup_uv] Done. Activate the venv with: source .venv/bin/activate"
